version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://banking_user:banking_pass@db:5432/banking_ml_platform
      - KAGGLE_USERNAME=${KAGGLE_USERNAME}
      - KAGGLE_KEY=${KAGGLE_KEY}
    depends_on:
      - db
    volumes:
      - ./data:/app/data
      - ./models:/app/models

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=banking_ml_platform
      - POSTGRES_USER=banking_user
      - POSTGRES_PASSWORD=banking_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: